-- MySQL Script generated by MySQL Workbench
-- Thu May 28 14:51:34 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mecanico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mecanico` ;

-- -----------------------------------------------------
-- Schema mecanico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mecanico` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mecanico` ;

-- -----------------------------------------------------
-- Table `mecanico`.`Vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Vehiculo` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Vehiculo` (
  `IdVehiculo` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(8) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Linea` VARCHAR(45) NOT NULL,
  `Modelo` INT NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Kilometraje` INT NOT NULL,
  PRIMARY KEY (`IdVehiculo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Placa_UNIQUE` ON `mecanico`.`Vehiculo` (`Placa` ASC);

CREATE UNIQUE INDEX `IdVehiculo_UNIQUE` ON `mecanico`.`Vehiculo` (`IdVehiculo` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(20) NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Movil` VARCHAR(12) NOT NULL,
  `Telefono` VARCHAR(12) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdCliente_UNIQUE` ON `mecanico`.`Cliente` (`IdCliente` ASC);

CREATE UNIQUE INDEX `Cedula_UNIQUE` ON `mecanico`.`Cliente` (`Cedula` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Mecanico` (
  `IdMecanico` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(20) NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(12) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdMecanico`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Cedula_UNIQUE` ON `mecanico`.`Mecanico` (`Cedula` ASC);

CREATE UNIQUE INDEX `IdMecanico_UNIQUE` ON `mecanico`.`Mecanico` (`IdMecanico` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Orden_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Orden_trabajo` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Orden_trabajo` (
  `IdOrden` INT NOT NULL AUTO_INCREMENT,
  `Numero_Orden` VARCHAR(50) NOT NULL,
  `Fecha_Ingreso` DATETIME NOT NULL,
  `Descripcion_cliente` VARCHAR(1000) NOT NULL,
  `Descripcion_taller` VARCHAR(1000) NOT NULL,
  `Fecha_salida` DATETIME NOT NULL,
  `Cambio_aceite` TINYINT(1) NOT NULL,
  `Cambio_correa` TINYINT(1) NOT NULL,
  `Cambio_embrague` TINYINT(1) NOT NULL,
  `Cambio_Frenos` TINYINT(1) NOT NULL,
  `IdVehiculo` INT NOT NULL,
  `IdCliente` INT NOT NULL,
  `IdMecanico` INT NOT NULL,
  `Total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`IdOrden`, `IdVehiculo`, `IdCliente`, `IdMecanico`),
  CONSTRAINT `fk_Orden_trabajo_Vehiculo`
    FOREIGN KEY (`IdVehiculo`)
    REFERENCES `mecanico`.`Vehiculo` (`IdVehiculo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orden_trabajo_Cliente`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `mecanico`.`Cliente` (`IdCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orden_trabajo_Mecanico`
    FOREIGN KEY (`IdMecanico`)
    REFERENCES `mecanico`.`Mecanico` (`IdMecanico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Orden_trabajo_Vehiculo` ON `mecanico`.`Orden_trabajo` (`IdVehiculo` ASC);

CREATE INDEX `fk_Orden_trabajo_Cliente` ON `mecanico`.`Orden_trabajo` (`IdCliente` ASC);

CREATE INDEX `fk_Orden_trabajo_Mecanico` ON `mecanico`.`Orden_trabajo` (`IdMecanico` ASC);

CREATE UNIQUE INDEX `Numero_Orden_UNIQUE` ON `mecanico`.`Orden_trabajo` (`Numero_Orden` ASC);

CREATE UNIQUE INDEX `IdOrden_UNIQUE` ON `mecanico`.`Orden_trabajo` (`IdOrden` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Detalle_orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Detalle_orden` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Detalle_orden` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `IdOrden` INT NOT NULL,
  PRIMARY KEY (`idDetalle`, `IdOrden`),
  CONSTRAINT `fk_Detalle_orden_Orden_trabajo`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `mecanico`.`Orden_trabajo` (`IdOrden`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mecanico`.`Detalle_orden` (`idDetalle` ASC);

CREATE INDEX `fk_Detalle_orden_Orden_trabajo` ON `mecanico`.`Detalle_orden` (`IdOrden` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Refacciones_Servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Refacciones_Servicios` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Refacciones_Servicios` (
  `IdRefacccion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Cantidad_stock` INT NOT NULL,
  `Precio_unidad` DECIMAL(10,2) NOT NULL,
  `Marca` VARCHAR(50) NOT NULL,
  `IdDetalle` INT NOT NULL,
  PRIMARY KEY (`IdRefacccion`, `IdDetalle`),
  CONSTRAINT `fk_Refacciones_Servicios_Detalle_orden`
    FOREIGN KEY (`IdDetalle`)
    REFERENCES `mecanico`.`Detalle_orden` (`idDetalle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mecanico`.`Refacciones_Servicios` (`IdRefacccion` ASC);

CREATE INDEX `fk_Refacciones_Servicios_Detalle_orden` ON `mecanico`.`Refacciones_Servicios` (`IdDetalle` ASC);


-- -----------------------------------------------------
-- Table `mecanico`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mecanico`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mecanico`.`Usuario` (
  `IdLogin` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(8) NOT NULL,
  `Tipo` VARCHAR(1) NOT NULL COMMENT '1 - Admin\n2 - Normal',
  `Estado` VARCHAR(1) NOT NULL COMMENT 'A - Activo\nI - Inactivo',
  PRIMARY KEY (`IdLogin`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Login_UNIQUE` ON `mecanico`.`Usuario` (`Login` ASC);

CREATE UNIQUE INDEX `IdLogin_UNIQUE` ON `mecanico`.`Usuario` (`IdLogin` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
